import { authoredEntity, all, near, property } from './authored.js';
import { createSpatialStage } from './engine.js';
import type { SpatialChapterDefinition, SpatialSceneDefinition, SpatialCondition, SpatialCycle } from './types';

const E = (id: string, name: string, x: number, y: number, kind = 'object', extra: Record<string, string | number | boolean> = {}) =>
  authoredEntity(id, name, '', x, y, { kind, ...(kind === 'lantern' ? { lit: true, lightRadius: 2.4 } : {}), ...extra }, { movable: kind === 'lantern' || kind === 'wedge' });
const Z = (entity: ReturnType<typeof E>, z: number) => ({ ...entity, location: { ...entity.location, z } });
const swingCycle = (entity: string, nearX: number[], safeX: number, baseY: number): SpatialCycle => ({
  entity, property: 'sweepTick', values: [...nearX.map((_, index) => `near-${index}`), ...Array(16).fill('far')],
  locations: [...nearX.map((x) => ({ x, y: baseY })), ...Array(16).fill({ x: safeX, y: baseY + 1.45 })],
});
const eitherHolding = (entity: string): SpatialCondition => ({ kind: 'any', conditions: [
  { kind: 'holding', actor: 'hero', entity }, { kind: 'holding', actor: 'keeper', entity },
] });
const together = (target: string): SpatialCondition => all(near('hero', target), near('keeper', target));
const floor = (from: number, to: number, y: number, enabled?: SpatialCondition) => ({ from, to, y, ...(enabled ? { enabled } : {}) });
const scene = (id: string, title: string, goal: string, heroX: number, heroY: number,
  entities: SpatialSceneDefinition['entities'], surfaces: SpatialSceneDefinition['surfaces'],
  bodies: SpatialSceneDefinition['bodies'], goals: SpatialCondition[], defaultTarget: string,
  rest: Partial<SpatialSceneDefinition> = {}): SpatialSceneDefinition => ({
  id, title, goal, entities: entities.map((entity) => ({ ...entity, location: { ...entity.location, region: id } })),
  hero: { location: { region: id, x: heroX, y: heroY } },
  surfaces, bodies, goals, defaultTarget, ...rest,
});

const fog: SpatialSceneDefinition[] = [
  scene('08-v2-1', '안개 속 다리', '안개 너머 출구로 건너가야 해요.', 0.8, 0.4,
    [E('fog', '옅어지는 안개', 4.8, 2, 'fog', { visibleRange: 1.5 }), E('bridge', '굽은 돌다리', 8.7, 2.8, 'bridge'),
      E('cliff', '낭떠러지', 5, 0, 'gap'), E('exit', '출구', 8.8, 2.8, 'exit')],
    [
      { ...floor(0, 3.05, 0.4), z: 0, depth: 3.4 },
      { ...floor(2.55, 3.8, 0.4), endY: 1.25, z: 1.2, depth: 1 },
      { ...floor(3.8, 4.7, 1.25), endY: 1.85, z: 0.65, depth: 1.8 },
      { ...floor(4.7, 5.8, 1.85), endY: 1.65, z: -0.3, depth: 2.2 },
      { ...floor(5.8, 6.8, 1.65), endY: 2.3, z: -0.8, depth: 1.6 },
      { ...floor(6.8, 7.5, 2.3), endY: 2.8, z: 0.1, depth: 1.8 },
      { ...floor(7.5, 9.3, 2.8), z: 0.2, depth: 1.7 },
    ],
    [{ entity: 'bridge', width: 1.15, height: 1.5, depth: 0.85, offsetX: -6.55, offsetY: -2.4, kind: 'solid' }],
    [near('hero', 'exit')], 'exit', {
      cycles: [{ entity: 'fog', property: 'visibleRange', values: [1.5, 2.4, 3.8, 5.5, 3.8, 2.4], ticksPerValue: 2 }],
      routes: { bridge: [{ x: 1.35, y: 0.4, z: 1.2 }, { x: 2.55, y: 0.4, z: 1.2 },
        { x: 3.8, y: 1.25, z: 1.2 }, { x: 4.7, y: 1.85, z: 0.65 },
        { x: 5.8, y: 1.65, z: -0.3 }, { x: 6.8, y: 2.3, z: -0.8 },
        { x: 7.5, y: 2.8, z: 0.1 }, { x: 8.7, y: 2.8, z: 0.2 }] },
    }),
  scene('08-v2-2', '끊긴 쪽 보기', '건너편 섬에 닿아야 해요.', 4.7, 0.4,
    [Z(E('leftBridge', '왼쪽 다리', 2.6, 1.2, 'bridge'), -1.2), Z(E('rightBridge', '오른쪽 다리', 8.8, 2.1, 'bridge'), 1.2),
      E('gap', '중앙 틈', 5, 0, 'gap'), Z(E('island', '도착 섬', 8.8, 2.1, 'exit'), 1.2)],
    [{ ...floor(4.2, 5.35, 0.4), z: 0, depth: 3.3 },
      { ...floor(2.6, 4.2, 1.2), endY: 0.4, z: -1.2, depth: 1 },
      { ...floor(5.35, 7.6, 0.4), endY: 1.2, z: 1.2, depth: 1 },
      { ...floor(7.6, 8.6, 1.2), endY: 2.1, z: 1.2, depth: 1 },
      { ...floor(8.6, 9.3, 2.1), z: 1.2, depth: 1 }], [],
    [near('hero', 'island')], 'island', {
      routes: { rightBridge: [{ x: 5.1, y: 0.4, z: 1.2 }, { x: 6.3, y: 0.7, z: 1.2 },
        { x: 7.6, y: 1.2, z: 1.2 }, { x: 8.8, y: 2.1, z: 1.2 }],
        leftBridge: [{ x: 4.3, y: 0.4, z: -1.2 }, { x: 3.3, y: 0.8, z: -1.2 }, { x: 2.6, y: 1.2, z: -1.2 }] },
    }),
  scene('08-v2-3', '바람 깃발', '바람길 너머로 가야 해요.', 0.9, 0.4,
    [E('flag', '신호 깃발', 2.6, 2.5, 'flag', { phase: 'flat' }),
      E('wind', '바람길', 4.5, 0.4, 'wind', { strength: 'strong', gustPhase: 'gust-0' }),
      E('alcove', '시작 오목벽', 1.4, 0.4, 'wall'), E('exit', '출구', 8.7, 0.4, 'exit')],
    [floor(0, 9.4, 0.4)], [{ entity: 'wind', width: 4.4, height: 1.4, kind: 'wind', active: property('wind', 'strength', 'strong') }],
    [near('hero', 'exit')], 'wind', {
      cycles: [{ entity: 'wind', property: 'gustPhase', values: [
        'gust-0', 'gust-1', 'gust-2', 'gust-3', 'gust-4', ...Array(16).fill('lull'),
      ] }],
      rules: [{ when: property('wind', 'gustPhase', 'lull'), effects: [
        { entity: 'wind', property: 'strength', value: 'weak', otherwise: 'strong' },
        { entity: 'flag', property: 'phase', value: 'drooped', otherwise: 'flat' },
      ] }],
    }),
  scene('08-v2-4', '등불의 윤곽', '안개 속 위층에 올라가야 해요.', 0.9, 0.4,
    [E('lantern', '등불', 1.5, 0.4, 'lantern'), Z(E('stairs', '안개 계단', 8.5, 3, 'stairs'), 0.2),
      E('gap', '옆 틈', 5.5, 0, 'gap'), Z(E('upper', '위층', 8.5, 3, 'exit'), 0.2)],
    [{ ...floor(0, 2.6, 0.4), z: 0, depth: 3.3 },
      { ...floor(2.6, 3.55, 0.4), endY: 0.9, z: 1.2, depth: 1 },
      { ...floor(3.55, 4.55, 0.9), endY: 1.45, z: 1.2, depth: 1 },
      { ...floor(4.55, 5.55, 1.45), endY: 1.9, z: -0.1, depth: 2.8 },
      { ...floor(5.55, 6.6, 1.9), endY: 2.45, z: -0.8, depth: 1.4 },
      { ...floor(6.6, 7.6, 2.45), endY: 3, z: 0.2, depth: 2.2 },
      { ...floor(7.6, 9.3, 3), z: 0.2, depth: 1.6 }], [], [near('hero', 'upper')], 'upper', {
      routes: { stairs: [{ x: 2.5, y: 0.4, z: 1.2 }, { x: 3.55, y: 0.9, z: 1.2 },
        { x: 4.55, y: 1.45, z: 1.2 }, { x: 5.55, y: 1.9, z: -0.1 },
        { x: 6.6, y: 2.45, z: -0.8 }, { x: 7.6, y: 3, z: 0.2 }, { x: 8.5, y: 3, z: 0.2 }] },
    }),
  scene('08-v2-5', '문양이 닿는 곳', '다리 너머 출구에 닿아야 해요.', 1, 0.5,
    [E('window', '관측창', 2.1, 1.5, 'window'), Z(E('triangle', '삼각 다리', 8.7, 1.25, 'bridge'), 1.2),
      Z(E('circle', '원형 다리', 4.7, 2.15, 'bridge'), -1.2), Z(E('exit', '출구', 8.7, 1.25, 'exit'), 1.2)],
    [{ ...floor(0, 3, 0.5), z: 0, depth: 3.3 },
      { ...floor(3, 3.8, 0.5), endY: 0.9, z: 1.2, depth: 1 },
      { ...floor(3.8, 7.3, 0.9), z: 1.2, depth: 1 },
      { ...floor(7.3, 8.2, 0.9), endY: 1.25, z: 1.2, depth: 1 },
      { ...floor(8.2, 9.4, 1.25), z: 1.2, depth: 1 },
      { ...floor(3, 4.7, 2.15), z: -1.2, depth: 1 }], [],
    [near('hero', 'exit')], 'exit', {
      routes: { triangle: [{ x: 2.9, y: 0.5, z: 1.2 }, { x: 3.8, y: 0.9, z: 1.2 },
        { x: 7.3, y: 0.9, z: 1.2 }, { x: 8.7, y: 1.25, z: 1.2 }],
        circle: [{ x: 2.9, y: 0.5, z: -1.2 }, { x: 4.7, y: 2.15, z: -1.2 }] },
    }),
  scene('08-v2-6', '출발 신호', '건너편 부두로 가야 해요.', 0.8, 0.5,
    [E('flag', '정박 깃발', 2.25, 1.8, 'flag'), E('boat', '나룻배', 2.8, 0.55, 'boat', { docked: false }),
      E('water', '물길', 5, 0, 'water'), E('dock', '도착 부두', 8.5, 2.1, 'exit')],
    [floor(0, 2.5, 0.5), floor(7.45, 9.5, 2.1)],
    [{ entity: 'boat', width: 1.2, height: 0.25, kind: 'solid', support: true }], [near('hero', 'dock')], 'boat', {
      interactions: [{ kind: 'transport', entity: 'boat', from: { x: 2.8, y: 0.55 }, to: { x: 7.5, y: 2.1 }, period: 8 }],
      cycles: [{ entity: 'boat', property: 'docked', values: [false, false, false, false, false, false, false, false,
        true, false, false, false, false, false, false, false] }],
    }),
];

const tower: SpatialSceneDefinition[] = [
  scene('09-v2-1', '기울어진 층계', '탑의 위층으로 올라가야 해요.', 0.9, 0.4,
    [E('wedge', '쐐기 받침', 1.5, 0.4, 'wedge'), E('stairs', '기울어진 계단', 3.6, 0.4, 'stairs', { stable: false }),
      E('upper', '위층', 8.4, 3.1, 'exit')],
    [floor(0, 3.5, 0.4), { ...floor(3.5, 4.2, 0.4, property('stairs', 'stable', true)), endY: 0.8 },
      { ...floor(4.2, 5.1, 0.8, property('stairs', 'stable', true)), endY: 1.4 },
      { ...floor(5.1, 6, 1.4, property('stairs', 'stable', true)), endY: 2 },
      { ...floor(6, 7.2, 2, property('stairs', 'stable', true)), endY: 3.1 }, floor(7.2, 9.4, 3.1)], [],
    [near('hero', 'upper')], 'stairs', {
      interactions: [{ kind: 'movable', entity: 'wedge', placements: { stairs: { x: 3.2, y: 0.4 } } }],
      rules: [{ when: near('wedge', 'stairs', 0.55), effects: [{ entity: 'stairs', property: 'stable', value: true, otherwise: false }] }],
    }),
  scene('09-v2-2', '종추의 틈', '종추 너머로 가야 해요.', 0.9, 0.4,
    [E('bell', '종추', 7.1, 0.4, 'bell', { phase: 'near', sweepTick: 'near-0' }), E('leftWall', '왼쪽 보호벽', 1.8, 0.4, 'wall'),
      E('rightWall', '오른쪽 보호벽', 7.3, 0.4, 'wall'), E('exit', '출구', 8.7, 0.4, 'exit')],
    [floor(0, 9.4, 0.4)],
    [{ entity: 'bell', width: 1.35, height: 3.4, kind: 'crush' }],
    [near('hero', 'exit')], 'bell', {
      cycles: [swingCycle('bell', [7.1, 6.3, 5.5, 4.8, 4.1, 3.3, 2.7, 3.3], 4.8, 0.4)], ceiling: 4,
      rules: [{ when: property('bell', 'sweepTick', 'far'), effects: [{ entity: 'bell', property: 'phase', value: 'far', otherwise: 'near' }] }],
    }),
  scene('09-v2-3', '이어진 풍로', '다음 층으로 올라가야 해요.', 0.9, 0.4,
    [E('panel', '바람판', 1.3, 0.4, 'wind-panel', { direction: 'side' }), E('duct', '연결 풍로', 3.2, 1.1, 'duct'),
      E('lift', '종탑 승강대', 5.1, 0.15, 'lift', { arrived: false }), E('upper', '위층', 8.4, 3.1, 'exit')],
    [floor(0, 4.6, 0.4), floor(5.8, 9.5, 3.1)],
    [{ entity: 'lift', width: 1.5, height: 0.25, kind: 'solid', support: true }],
    [near('hero', 'upper')], 'lift', {
      interactions: [{ kind: 'control', entity: 'panel', property: 'direction', value: 'lift', offValue: 'side',
        destinations: { lift: 'lift', duct: 'lift' } },
        { kind: 'transport', entity: 'lift', from: { x: 5.1, y: 0.15 }, to: { x: 5.1, y: 2.85 }, period: 20,
          enabled: property('panel', 'direction', 'lift') }],
      cycles: [{ entity: 'lift', property: 'arrived', values: Array.from({ length: 40 }, (_, index) => index === 20) }],
    }),
  scene('09-v2-4', '어두운 층계', '등불을 가지고 층계를 올라가야 해요.', 0.9, 0.4,
    [E('lantern', '등불', 1.4, 0.4, 'lantern'), Z(E('stairs', '꺾인 계단', 8.6, 3, 'stairs'), 0.2),
      E('gap', '어두운 틈', 5.2, 0, 'gap'), Z(E('exit', '출구', 8.6, 3, 'exit'), 0.2)],
    [{ ...floor(0, 2.6, 0.4), z: 0, depth: 3.3 },
      { ...floor(2.6, 3.6, 0.4), endY: 0.95, z: 1.2, depth: 1 },
      { ...floor(3.6, 4.6, 0.95), endY: 1.55, z: 1.2, depth: 1 },
      { ...floor(4.6, 5.6, 1.55), endY: 2.1, z: -0.1, depth: 2.8 },
      { ...floor(5.6, 6.7, 2.1), endY: 2.55, z: -0.8, depth: 1.4 },
      { ...floor(6.7, 7.6, 2.55), endY: 3, z: 0.2, depth: 2.2 },
      { ...floor(7.6, 9.4, 3), z: 0.2, depth: 1.6 }], [],
    [near('hero', 'exit')], 'exit', {
      routes: { stairs: [{ x: 2.5, y: 0.4, z: 1.2 }, { x: 3.6, y: 0.95, z: 1.2 },
        { x: 4.6, y: 1.55, z: 1.2 }, { x: 5.6, y: 2.1, z: -0.1 },
        { x: 6.7, y: 2.55, z: -0.8 }, { x: 7.6, y: 3, z: 0.2 }, { x: 8.6, y: 3, z: 0.2 }] },
    }),
  scene('09-v2-5', '서로 기다리는 층', '등지기와 건너편에서 만나야 해요.', 0.9, 0.4,
    [E('handle', '유지 손잡이', 2.2, 1.05, 'handle'), E('bridge', '연결 다리', 5, 0.5, 'bridge', { down: false }),
      E('ratchet', '끝 고정 톱니', 7.1, 0.5, 'ratchet', { locked: false }), E('meeting', '합류 자리', 8.7, 0.5, 'exit')],
    [floor(0, 2.8, 0.5), floor(2.8, 7, 0.5, property('bridge', 'down', true)), floor(7, 9.5, 0.5)], [],
    [together('meeting')], 'bridge', {
      keeper: { location: { region: '09-v2-5', x: 1.4, y: 0.5 } },
      interactions: [{ kind: 'handle', entity: 'handle' }],
      rules: [
        { when: { kind: 'any', conditions: [eitherHolding('handle'), property('ratchet', 'locked', true)] },
          effects: [{ entity: 'bridge', property: 'down', value: true, otherwise: false }] },
        { when: { kind: 'any', conditions: [near('hero', 'ratchet'), near('keeper', 'ratchet')] },
          effects: [{ entity: 'ratchet', property: 'locked', value: true }] },
      ],
    }),
  scene('09-v2-6', '종 위의 문', '함께 종 너머의 문에 닿아야 해요.', 0.9, 0.4,
    [E('window', '관측창', 2.1, 1.6, 'window'), E('bell', '움직이는 큰 종', 6.3, 0.4, 'bell', { phase: 'near', sweepTick: 'near-0' }),
      E('alcove', '중간 피난 홈', 7, 0.4, 'alcove'), E('door', '문', 8.8, 0.4, 'exit')],
    [floor(0, 9.5, 0.4)], [{ entity: 'bell', width: 1.7, height: 3.3, kind: 'crush' }],
    [together('door')], 'bell', {
      keeper: { location: { region: '09-v2-6', x: 1.4, y: 0.4 } },
      cycles: [swingCycle('bell', [6.3, 5.8, 5.2, 4.8, 4.2, 3.8, 3.5, 3.8], 5, 0.4)], ceiling: 4,
      rules: [{ when: property('bell', 'sweepTick', 'far'), effects: [{ entity: 'bell', property: 'phase', value: 'far', otherwise: 'near' }] }],
    }),
];

const warden: SpatialSceneDefinition[] = [
  scene('10-v2-1', '팔이 비킨 자리', '팔 너머 안전한 자리로 가야 해요.', 0.9, 0.5,
    [E('arm', '문지기 팔', 7.1, 0.5, 'arm', { phase: 'near', sweepTick: 'near-0' }), E('shield', '시작 방패벽', 1.6, 0.5, 'wall'),
      E('alcove', '가슴 아래 홈', 5.5, 0.5, 'alcove'), E('platform', '오른쪽 발판', 8.5, 0.5, 'exit')],
    [floor(0, 9.5, 0.5)], [{ entity: 'arm', width: 1.4, height: 3.5, kind: 'crush' }],
    [together('platform')], 'arm', {
      keeper: { location: { region: '10-v2-1', x: 1.4, y: 0.5 } },
      cycles: [swingCycle('arm', [7.1, 6.4, 5.7, 5, 4.3, 3.6, 2.7, 3.6], 4.8, 0.5)], ceiling: 4,
      rules: [{ when: property('arm', 'sweepTick', 'far'), effects: [{ entity: 'arm', property: 'phase', value: 'far', otherwise: 'near' }] }],
    }),
  scene('10-v2-2', '첫 갑옷', '첫 갑옷 너머로 가야 해요.', 0.9, 0.6,
    [E('latch', '갑옷 걸쇠', 2.8, 1.3, 'latch', { unlocked: false }),
      E('plate', '갑옷판', 3.5, 0.6, 'plate', { down: false }), E('gap', '아래 틈', 5.1, 0, 'gap'),
      E('platform', '건너편 발판', 8.2, 0.9, 'exit')],
    [floor(0, 3.4, 0.6), { ...floor(3.4, 4, 0.6, property('plate', 'down', true)), endY: 0.9 },
      floor(4, 6.95, 0.9, property('plate', 'down', true)), floor(6.95, 9.5, 0.9)],
    [{ entity: 'plate', width: 0.45, height: 3.4, kind: 'solid', kinematic: true, active: property('plate', 'down', false) }],
    [together('platform')], 'plate', {
      keeper: { location: { region: '10-v2-2', x: 1.4, y: 0.6 } },
      interactions: [{ kind: 'control', entity: 'latch', property: 'unlocked', value: true }],
      rules: [{ when: property('latch', 'unlocked', true), effects: [{ entity: 'plate', property: 'down', value: true, otherwise: false }] }],
    }),
  scene('10-v2-3', '뜨거운 틈', '갑옷 안쪽으로 들어가야 해요.', 0.9, 0.5,
    [E('panel', '냉각 바람판', 1.9, 1, 'wind-panel', { direction: 'away' }),
      E('path', '달아오른 갑옷길', 5, 0.7, 'heated-path', { hot: true }),
      E('shield', '시작 차폐벽', 1.4, 0.5, 'wall'), E('platform', '안쪽 발판', 8.5, 1, 'exit')],
    [floor(0, 9.4, 0.5)], [{ entity: 'path', width: 4.5, height: 0.2, kind: 'heat', active: property('path', 'hot', true) }],
    [together('platform')], 'path', {
      keeper: { location: { region: '10-v2-3', x: 1.4, y: 0.5 } },
      interactions: [{ kind: 'control', entity: 'panel', property: 'direction', value: 'path', offValue: 'away',
        destinations: { path: 'path' } }],
      rules: [{ when: property('panel', 'direction', 'path'), effects: [{ entity: 'path', property: 'hot', value: false, otherwise: true }] }],
    }),
  scene('10-v2-4', '접힌 날개', '문지기의 가슴 앞에 닿아야 해요.', 0.9, 0.4,
    [E('panel', '방향 바람판', 2.3, 0.4, 'wind-panel', { direction: 'away' }),
      E('wing', '문지기 날개', 5.5, 1.7, 'wing', { folded: false }),
      E('cliff', '옆 낭떠러지', 6, 0, 'gap'), E('platform', '가슴 앞 발판', 8.5, 3.1, 'exit')],
    [floor(0, 3.5, 0.4), { ...floor(3.5, 4.4, 0.4, property('wing', 'folded', true)), endY: 1 },
      { ...floor(4.4, 5.3, 1, property('wing', 'folded', true)), endY: 1.65 },
      { ...floor(5.3, 6.2, 1.65, property('wing', 'folded', true)), endY: 2.3 },
      { ...floor(6.2, 7.2, 2.3, property('wing', 'folded', true)), endY: 3.1 }, floor(7.2, 9.5, 3.1)],
    [{ entity: 'wing', width: 1.2, height: 2.5, kind: 'solid', kinematic: true, active: property('wing', 'folded', false) }],
    [together('platform')], 'wing', {
      keeper: { location: { region: '10-v2-4', x: 1.4, y: 0.4 } },
      interactions: [{ kind: 'control', entity: 'panel', property: 'direction', value: 'hinge', offValue: 'away',
        destinations: { wing: 'hinge' } }],
      rules: [{ when: property('panel', 'direction', 'hinge'), effects: [{ entity: 'wing', property: 'folded', value: true, otherwise: false }] }],
    }),
  scene('10-v2-5', '마지막 매듭', '마지막 걸쇠를 풀어 문지기를 자유롭게 해 줘요.', 1, 0.5,
    [E('ring', '유지 고리', 2.6, 1, 'handle'), E('rope', '연결 줄', 4.2, 1.8, 'rope', { taut: false }),
      E('latch', '마지막 걸쇠', 6, 3, 'latch', { lowered: false, unlocked: false }),
      E('chest', '문지기 가슴문', 8, 2, 'door', { open: false })],
    [floor(0, 9.5, 0.5)], [], [property('chest', 'open', true)], 'ring', {
      keeper: { location: { region: '10-v2-5', x: 1.5, y: 0.5 } },
      interactions: [{ kind: 'handle', entity: 'ring' }, { kind: 'control', entity: 'latch', property: 'unlocked', value: true }],
      rules: [
        { when: eitherHolding('ring'), effects: [
          { entity: 'rope', property: 'taut', value: true, otherwise: false },
          { entity: 'latch', property: 'lowered', value: true, otherwise: false },
        ], locations: [{ entity: 'latch', x: 6, y: 1.15, otherwise: { x: 6, y: 3 } }] },
        { when: property('latch', 'unlocked', true), effects: [{ entity: 'chest', property: 'open', value: true, otherwise: false }] },
      ],
    }),
  scene('10-v2-6', '돌아가는 문', '등지기와 함께 마지막 문을 지나야 해요.', 0.9, 0.5,
    [E('door', '되감기는 마지막 문', 5, 0.5, 'door', { open: false }),
      E('outer', '바깥 손잡이', 4, 1.1, 'handle'), E('inner', '안쪽 손잡이', 6.1, 1.1, 'handle'),
      E('exit', '문 너머 자리', 8.5, 0.5, 'exit')],
    [floor(0, 9.5, 0.5)],
    [{ entity: 'door', width: 0.5, height: 3.5, kind: 'solid', kinematic: true, active: property('door', 'open', false) }],
    [together('exit')], 'door', {
      keeper: { location: { region: '10-v2-6', x: 1.4, y: 0.5 } }, ceiling: 4,
      interactions: [{ kind: 'door', entity: 'door', spring: true }, { kind: 'handle', entity: 'outer' }, { kind: 'handle', entity: 'inner' }],
      rules: [{ when: { kind: 'any', conditions: [eitherHolding('outer'), eitherHolding('inner')] },
        effects: [{ entity: 'door', property: 'open', value: true, otherwise: false }] }],
    }),
];

export const SPATIAL_LATE_DEFINITIONS: SpatialChapterDefinition[] = [
  { id: 8, title: '안개 신호장', objective: '안개 너머 길을 살피며 부두에 닿아요.', scenes: fog,
    story: { afterSegment: '08-v2-6', object: 'cargo-tag', text: '먼저 보고 말해 주던 네가 있었지.' } },
  { id: 9, title: '종탑의 안쪽', objective: '배운 길을 이어 탑의 문까지 올라가요.', scenes: tower,
    story: { afterSegment: '09-v2-6', object: 'railing-note', text: '이번에는 네가 먼저 종을 울렸네.' } },
  { id: 10, title: '돌아오지 못한 문지기', objective: '문지기의 장치를 풀고 등지기와 함께 나가요.', scenes: warden,
    story: { afterSegment: '10-v2-6', object: 'letter', text: '여기까지는 내가 길을 적었어. 다음 길은 네가 골라 줘. 이제는 같이 가자.' } },
];
export const SPATIAL_LATE_STAGES = SPATIAL_LATE_DEFINITIONS.map(createSpatialStage);
