import type { Entity, Scalar, WorldState } from "./types";

export const MATERIAL_LABELS: Record<Entity["material"], string> = {
  wood: "나무",
  cork: "코르크",
  stone: "돌",
  metal: "금속",
  glass: "유리",
  cloth: "천",
  water: "물",
  light: "빛",
};

const ENUM_LABELS: Record<string, string> = {
  none: "없음",
  unknown: "아직 모름",
  small: "작은 크기",
  large: "큰 크기",
  equipment: "몸에 매단 여정 물품",
  left: "왼쪽",
  right: "오른쪽",
  middle: "가운데",
  east: "동쪽",
  west: "서쪽",
  up: "위쪽",
  down: "아래쪽",
  drain: "배수로",
  exit: "출구",
  semicircle: "반달 모양",
  bridge: "다리",
  bypass: "우회로",
  closed: "닫힌 길",
  off: "꺼짐",
  hammer: "망치 아래",
  cooling: "식힘 자리",
  carrier: "운반대",
  fixed: "고정 정거장",
  safe: "안전 자리",
  portable: "이동 정거장",
  "cold-nozzle": "찬 바람 구멍",
  "left-fill": "왼쪽 채움 자리",
  center: "가운데",
  "right-drain": "오른쪽 배수대",
  recovery: "회수 자리",
  scale: "출구 저울",
  oven: "오븐 쪽",
  service: "옆길",
  "service-exit": "옆길 출구",
  "central-exit": "중앙 출구",
  "upstream-pressure-room": "상류 압력실",
  "routing-room": "분기실",
  "bridge-room": "다리 구역",
  star: "별 문양",
  moon: "달 문양",
  leaf: "잎 문양",
  serving: "완성 접시",
  pour: "붓기",
  ovens: "오븐",
  steam: "김 배출관",
  claw: "회전 집게",
  table: "식탁",
  soft: "말랑함",
  hard: "단단함",
  flat: "납작함",
  rising: "부푸는 중",
  platform: "발판 크기",
  overexpanded: "과팽창",
  burst: "터짐",
  collapsed: "꺼짐",
  raised: "올라온 상태",
  lowered: "내려간 상태",
  approach: "접근",
  sweep: "작동",
  away: "이탈 완료",
  home: "대기 위치",
  venting: "김 배출 중",
  stopped: "멈춤",
  "oven-bell": "오븐 종",
  "steam-venting": "김 배출",
  "steam-stopped": "김 멎음",
  "claw-sweep": "집게 왕복",
  "claw-away": "집게 이탈 완료",
  "table-aligned": "식탁 정렬",
  hot: "뜨거움",
  cold: "식음",
  "heat-on": "열원 켜짐",
  "dry-air": "마른 바람",
  strip: "띠 모양",
  straight: "곧은 모양",
  folded: "접힌 상태",
  extended: "펼쳐진 상태",
  low: "낮은 높이",
  enough: "충분한 높이",
  excessive: "너무 높은 상태",
  unfixed: "고정되지 않음",
  "moon-fixed": "달 문양에 고정됨",
  "cooled-bell": "식은 종",
  "cools-when-damper-closed": "열기 차단판을 닫으면 식음",
  "cooled-pattern-will-sag": "식은 무늬가 다시 처질 수 있음",
  rope: "밧줄",
  tongs: "긴 집게",
  normal: "바닥 방향",
  sun: "해 문양",
  drop: "물방울 문양",
  covered: "덮임",
  exposed: "노출됨",
  vine: "덩굴길",
  floor: "바닥길",
  vertical: "세로선",
  horizontal: "가로선",
  striped: "줄무늬 손잡이",
  round: "둥근 손잡이",
  triangle: "삼각 손잡이",
  "brass-key": "놋쇠 열쇠",
  lantern: "등불",
  mirror: "반사경",
  counterweight: "도르래 추",
  striker: "점화쇠",
  lens: "렌즈",
  "rope-loop": "밧줄 고리",
  start: "출발 쪽",
  destination: "도착 쪽",
  lower: "아래층",
  upper: "위층",
  empty: "비어 있음",
  "hook-1": "첫째 고리",
  "hook-2": "둘째 고리",
  "lower-locked": "아래층에 브레이크 잠김",
  "upper-locked": "위층에 브레이크 잠김",
  released: "브레이크 풀림",
  incomplete: "아직 완성되지 않음",
  "lamps-ready": "등불 둘 준비됨",
  "mirrors-ready": "반사경 둘 준비됨",
  "mirrors-missing": "반사경이 아직 비어 있음",
  "lamps-missing": "등불이 아직 비어 있음",
  "seal-chest": "인장 상자",
  "alarm-eye": "경보 눈",
  elevator: "화물 승강칸",
  "cargo-basket": "작은 화물 바구니",
  "cargo-winch": "화물 손윈치",
  footway: "물길 발디딤대",
  lamp: "조명 불꽃",
  cart: "수레",
  crank: "크랭크",
  neutral: "중립 위치",
  "right-high": "오른쪽 판이 올라감",
  "left-high": "왼쪽 레일이 올라감",
  "side-ladder": "측면 사다리",
  "right-platform": "오른쪽 승강판",
  "keeper-rail": "등지기 레일",
  "hero-crossing": "용사 건넘",
  "ceiling-rope": "천장 밧줄",
  "rail-rope": "레일 밧줄",
  "hero-push": "용사가 밂",
  latch: "걸쇠",
  light: "빛",
  eye: "경보 눈",
  shutter: "셔터",
  "lamp-a": "첫째 등불",
  "lamp-b": "둘째 등불",
  "mirror-a": "첫째 반사경",
  "mirror-b": "둘째 반사경",
  "receiver-a": "첫째 수광판",
  "receiver-b": "둘째 수광판",
};

const PROPERTY_LABELS: Record<string, string> = {
  equipment: "몸에 매단 물품",
  accessible: "접근 가능",
  accepts: "받을 수 있는 물건",
  acceptsCorner: "모서리 고정 가능",
  acceptsIdentity: "받는 문양",
  acceptsLever: "레버 결합 가능",
  acceptsShape: "받는 모양",
  acceptsWedge: "쐐기 고정 가능",
  active: "현재 작동",
  afloat: "현재 부유",
  landingReachable: "건너편 발판까지 거리",
  aligned: "출구와 정렬",
  amount: "담긴 양",
  apertureWidth: "홈 너비",
  armed: "다음 정렬에 걸림",
  barrelHeight: "통 높이",
  baseShape: "밑면 모양",
  bell: "종 울림",
  bellCapacity: "종 수용량",
  boardable: "탑승 가능",
  broken: "파손 상태",
  bodyClear: "본체 통과 완료",
  buoyant: "물에 뜨는 성질",
  capacity: "표시 용량",
  catchesAt: "걸리는 위치",
  catchesDough: "반죽 받침",
  catchesFall: "추락 받침",
  causeMapOnly: "원인 지도 전용",
  causeMapVisible: "원인 지도 표시",
  chainLinks: "사슬 길이",
  climbable: "올라설 수 있음",
  coached: "안내 완료",
  cooled: "식힘 완료",
  cooledAt: "식힌 곳",
  cooledWidth: "식은 너비",
  collision: "충돌",
  collapsed: "꺼짐",
  connectedFrom: "힘을 받는 곳",
  connectedTo: "연결 대상",
  contact: "위험물 접촉",
  controls: "조절 대상",
  cooling: "식힘 진행",
  coolingMethod: "식히는 방법",
  coolingPerTick: "한 단계마다 식는 양",
  cornerFitsStop: "모서리 고정 홈에 맞음",
  cutoffState: "열 차단 상태",
  cycling: "반복 작동 중",
  cycle: "반복 순서",
  dangerEnd: "위험 구간 끝",
  dangerStart: "위험 구간 시작",
  direction: "방향",
  dry: "마른 상태",
  effectivePressure: "실제 전달 압력",
  emptiesAt: "비워지는 곳",
  emptyCircle: "빈 원 표식",
  endMark: "끝 눈금",
  event: "현재 사건",
  exitLevel: "출구 높이",
  exitOrientation: "출구 방향",
  extended: "다리 펼침",
  firmness: "단단함",
  fitsWhen: "맞는 상태",
  fixed: "고정됨",
  fixedDirection: "방향 고정",
  fixedGrate: "식힘판 고정",
  floodMark: "시작점 침수 눈금",
  flow: "흐르는 양",
  flowDirection: "흐름 방향",
  flowDistance: "흐르는 거리",
  flowing: "현재 흐름",
  flowSpeed: "흐름 세기",
  fluttering: "바람에 나부낌",
  fluidDensity: "물의 밀도",
  form: "현재 형태",
  formedAt: "형태를 만든 곳",
  grilleOpenings: "식힘판 틈",
  growthArea: "부풀 수 있는 자리",
  growthPerTick: "한 단계마다 부푸는 양",
  handleHeight: "손잡이 높이",
  handleVisible: "손잡이 보임",
  heatMarks: "온도 눈금 수",
  heatState: "열 상태",
  heated: "가열 중",
  height: "높이",
  heldWith: "잡고 있는 도구",
  heroHeight: "용사 높이",
  holdable: "잡아 유지 가능",
  hook: "갈고리",
  hooked: "갈고리에 고정",
  identity: "테두리 문양",
  latchMark: "걸쇠 표식",
  latched: "걸쇠 고정",
  level: "현재 높이",
  linkedDevice: "연결 장치",
  load: "현재 하중",
  loadMark: "하중 눈금",
  locked: "잠김",
  locksToCarrier: "운반대에 고정 가능",
  lowerLatch: "아래 걸쇠",
  loweredWhenRaised: "추가 오르면 내려감",
  markedWeight: "표시 무게",
  marks: "눈금",
  knots: "매듭 수",
  moonMark: "달 표식",
  moonStamp: "달 각인",
  on: "걸쇠 작동",
  open: "열림",
  opensWhen: "열리는 조건",
  orientation: "현재 방향",
  outsideClawRange: "집게 범위 밖",
  outsideHammerRange: "망치 범위 밖",
  overloadAmount: "과부하 기준",
  overflowMark: "범람 눈금",
  passiveCooling: "스스로 식음",
  phase: "현재 단계",
  position: "현재 자리",
  positions: "이동 자리 순서",
  powered: "동력 공급",
  pressure: "현재 압력",
  pressureReduction: "압력 감소량",
  pullFraction: "당긴 정도",
  pulled: "당겨짐",
  raised: "올라감",
  range: "작동 범위",
  rangeEnd: "작동 범위 끝",
  rangeStart: "작동 범위 시작",
  reachArc: "닿는 호의 길이",
  reaches: "닿는 정거장",
  recovered: "회수됨",
  rejectedIdentity: "거부된 문양",
  released: "놓임",
  releasesAtPressure: "풀리는 압력",
  requiredAmount: "필요한 양",
  requiredFlow: "필요한 흐름",
  requiredHits: "필요한 타격 수",
  requiresDryPassage: "마른 통로 필요",
  requiresHeatCutoff: "열 차단 필요",
  requiredWeight: "필요한 무게",
  returnsToStart: "시작점으로 돌아옴",
  ropeLength: "밧줄 길이",
  route: "현재 경로",
  routes: "선택 가능한 경로",
  running: "현재 이동 중",
  safe: "안전",
  safeAmount: "안전한 양",
  safeHandle: "차가운 손잡이",
  safeToCross: "건널 수 있음",
  sees: "볼 수 있는 장치",
  sequence: "사건 순서",
  serving: "완성 접시 수",
  shape: "모양",
  slot: "운반 구분",
  shelterCapacity: "차양 수용량",
  silhouette: "보이는 윤곽",
  size: "현재 크기",
  soft: "부드러운 상태",
  spinning: "회전 중",
  stability: "다리 안정 상태",
  stable: "안정",
  stampHits: "각인 타격 수",
  starStamp: "별 각인",
  station: "현재 정거장",
  stations: "이용 가능한 정거장",
  staysReleased: "놓은 뒤에도 유지",
  stopped: "멈춤",
  stoppedAt: "멈춘 자리",
  stops: "멈추는 장치",
  stoppable: "멈출 수 있음",
  story: "발견한 기억",
  struck: "부딪힘",
  supported: "받침 있음",
  suppliesWind: "바람 공급",
  temperature: "현재 온도",
  tiePoint: "묶을 수 있음",
  tipped: "기울어짐",
  tool: "도구 종류",
  upperMark: "위 눈금",
  through: "통과 장치",
  visibleFunction: "보이는 작동 원리",
  visibleState: "보이는 상태",
  warning: "주의 상태",
  wedge: "쐐기로 사용 가능",
  weightMark: "무게 표식",
  wetRisk: "젖을 위험",
  width: "너비",
  zone: "현재 구역",
  zonePath: "구역 이동 순서",
  acceptsKey: "받는 열쇠",
  acceptsTrack: "이어지는 레일",
  choices: "사다리가 향할 수 있는 방",
  accessReady: "씨앗에 닿을 수 있음",
  actorOnly: "용사만 통과",
  alarmCause: "경보가 닫히는 원인",
  arrowVisible: "중력 화살표 보임",
  autoUnload: "도착 시 자동 인출",
  beams: "완성된 광선 갈래",
  belowSeed: "씨앗 아래 맞춤 홈",
  brassKeys: "놋쇠 열쇠 수",
  brakeMark: "브레이크 표시",
  braked: "층 브레이크 잠김",
  capacityItems: "물건 수용량",
  carriedAt: "현재 소지 위치",
  closes: "닫히는 장치",
  closesAfterTicks: "닫히기까지 박자",
  closeDelayTicks: "닫힘 유예 박자",
  closingBeat: "현재 닫힘 박자",
  connectedRegion: "연결된 방",
  counterweights: "도르래 추 수",
  coveredBy: "덮는 석판",
  danger: "위험 상태",
  directions: "표시된 중력 방향",
  distanceMarks: "거리 눈금",
  dustVisible: "흙가루 보임",
  extinguishesWicks: "심지를 끄는 물길",
  fixedGravity: "중력 방향 고정",
  fixedHooks: "고정 고리 수",
  fixedToPot: "화분에 고정",
  fixedWhenMoving: "운행 중 고정 필요",
  floorNumber: "표시 층 번호",
  fromRegion: "출발 방",
  gravity: "이 방의 중력 방향",
  heroReach: "용사가 닿는 높이",
  hand: "손에 든 물건",
  handCapacity: "손 수용량",
  handSlots: "필요한 손 칸",
  handUsed: "손 사용 중",
  handleMark: "손잡이 표식",
  handleShape: "손잡이 모양",
  heldSlots: "현재 든 손 칸",
  holdsDoor: "문을 여는 홈",
  hookCapacity: "고리 수용량",
  hooks: "고리에 건 물건",
  hooksUsed: "사용 중인 고리 수",
  illuminated: "빛을 받고 있음",
  ladder: "사다리",
  lanterns: "등불 수",
  lightRadius: "빛 반경",
  lit: "켜진 상태",
  loadMarks: "적재 눈금",
  locksCover: "석판 걸쇠를 잠그는 홈",
  mirrors: "반사경 수",
  moves: "움직이는 대상",
  movingTo: "이동 중인 층",
  opens: "여는 대상",
  opensAt: "열리는 기준 눈금",
  optional: "선택 소품",
  observedLoad: "확인된 하중",
  parentDevice: "연결된 본체",
  path: "현재 광선 경로",
  passageBlocked: "통로 막힘",
  persistentOpen: "열린 상태 유지",
  placed: "놓인 씨앗 수",
  potsCross: "화분 통과 가능",
  pressed: "눌림",
  raisesLift: "승강판을 올리는 홈",
  reading: "현재 균형 눈금",
  radius: "빛 센서 반경",
  radiusMark: "바닥 반경 눈금",
  railFixed: "레일에 고정",
  readable: "읽을 수 있음",
  receiver: "수광판",
  recoverable: "회수 가능",
  reinforced: "보강됨",
  relightable: "다시 점화 가능",
  relightsWicks: "심지 재점화 가능",
  required: "필요한 수",
  requiredBeams: "필요한 광선 갈래",
  requiresLitLantern: "켜진 등불 필요",
  requiresTwoHands: "두 손 필요",
  returnsTo: "돌아오는 곳",
  returned: "반납됨",
  safeRope: "안전 밧줄",
  scaleContribution: "균형막대에 더하는 눈금",
  selected: "현재 선택 경로",
  shapes: "필요한 문양",
  toRegion: "도착 방",
  track: "고정 레일 구간",
  transportRoute: "운반 경로",
  underThreshold: "턱 아래 맞춤 홈",
  unlocked: "잠금 해제",
  usedWallHook: "벽걸이 사용함",
  visible: "윤곽 보임",
  exit: "출구 레일",
  jump: "점프 가능",
  raises: "올리는 장치",
  accessRoute: "발코니 도달 경로",
  alignment: "현재 회전교 방향",
  carryCapacity: "등지기 운반 수용량",
  carrySize: "등지기가 드는 물건 크기",
  causalControl: "이 상태를 바꾸는 장치",
  causalControls: "열림 조건 장치",
  causalTarget: "유지로 바뀌는 상태",
  centered: "중앙 표식에 맞음",
  closingBeats: "전체 닫힘 박자",
  closingBeatsRemaining: "남은 닫힘 박자",
  curtainCloseBeats: "막 닫힘 박자",
  fits: "맞는 홈",
  flame: "불꽃 유지",
  handoffs: "역할 넘김 횟수",
  heroArrived: "용사 도착",
  heroTravelCells: "용사 통로 거리",
  held: "현재 유지 중",
  heldBy: "현재 유지 주체",
  holdCapacity: "동시 유지 수",
  holders: "가로대를 잡은 주체",
  high: "올라간 상태",
  keeperAllowed: "등지기 이용 가능",
  keeperTravelCells: "등지기 레일 거리",
  loaded: "평형추가 놓임",
  lockedAlignment: "잠긴 회전교 방향",
  lockedBy: "잠근 주체",
  lockedPosition: "잠긴 승강 축 위치",
  lowered: "지선 내려옴",
  maxWeight: "등지기 최대 운반 무게",
  rail: "등지기 레일",
  railOnly: "레일에서만 이동",
  requiredTurns: "필요한 크랭크 회전",
  ropeConnected: "수레 밧줄 연결",
  safeBeat: "완료한 안전 박자",
  snuffed: "불꽃 꺼짐",
  stairs: "계단 이동",
  support: "현재 받침",
  wedged: "쐐기로 받침",
};

const HIDDEN_PROPERTIES = new Set([
  "kind",
  "driftAge",
  "periodTicks",
  "publicLabel",
  "railSocket",
  "darkTicks",
  "usedWallHook",
  "holdEffectEntity",
  "holdEffectProperty",
  "holdEffectValue",
  "releaseEffectValue",
]);

const QUANTITY_UNITS: Partial<Record<string, string>> = {
  beams: "갈래",
  brassKeys: "개",
  capacityItems: "개",
  closeDelayTicks: "박",
  closesAfterTicks: "박",
  closingBeat: "박",
  counterweights: "개",
  distanceMarks: "칸",
  fixedHooks: "개",
  floorNumber: "층",
  handCapacity: "칸",
  handSlots: "칸",
  heldSlots: "칸",
  hookCapacity: "칸",
  hooksUsed: "칸",
  lanterns: "개",
  lightRadius: "칸",
  mirrors: "개",
  opensAt: "눈금",
  observedLoad: "눈금",
  placed: "개",
  radius: "칸",
  radiusMark: "칸",
  reading: "눈금",
  required: "개",
  requiredBeams: "갈래",
  requiredWeight: "눈금",
  scaleContribution: "눈금",
  carryCapacity: "개",
  closingBeats: "박",
  closingBeatsRemaining: "박",
  curtainCloseBeats: "박",
  handoffs: "번",
  heroTravelCells: "칸",
  holdCapacity: "개",
  keeperTravelCells: "칸",
  maxWeight: "눈금",
  requiredTurns: "번",
  safeBeat: "박",
};

const BOOLEAN_VALUES: Record<string, readonly [string, string]> = {
  accessible: ["접근 가능", "접근 불가"],
  active: ["작동 중", "멈춤"],
  afloat: ["물에 떠 있음", "떠 있지 않음"],
  landingReachable: ["발판에 내릴 수 있는 거리", "아직 발판과 멂"],
  aligned: ["출구와 맞음", "출구와 어긋남"],
  armed: ["다음 정렬에 걸림", "아직 걸리지 않음"],
  bell: ["종이 울림", "종이 울리지 않음"],
  boardable: ["올라탈 수 있음", "올라탈 수 없음"],
  broken: ["부서짐", "부서지지 않음"],
  bodyClear: ["본체까지 지나감", "본체가 아직 지나가는 중"],
  buoyant: ["물에 뜸", "물에 뜨지 않음"],
  climbable: ["올라설 수 있음", "올라설 수 없음"],
  cooled: ["식힘 완료", "아직 뜨거움"],
  contact: ["위험물에 닿음", "위험물에 닿지 않음"],
  collision: ["충돌함", "충돌 없음"],
  dry: ["마름", "젖음"],
  equipment: ["손·고리와 별도로 몸에 매고 있음", "몸에 매고 있지 않음"],
  emptyCircle: ["빈 원 표식", "다른 표식"],
  extended: ["펼쳐짐", "접혀 있음"],
  fixed: ["고정됨", "움직일 수 있음"],
  flowing: ["흐르는 중", "흐르지 않음"],
  holdable: ["잡아 유지 가능", "잡을 수 없음"],
  hooked: ["갈고리에 고정됨", "갈고리에 고정되지 않음"],
  latched: ["걸쇠에 고정됨", "걸쇠가 풀림"],
  locked: ["잠김", "잠기지 않음"],
  on: ["작동 중", "해제됨"],
  open: ["열림", "닫힘"],
  powered: ["동력 있음", "동력 없음"],
  raised: ["올라감", "내려감"],
  recovered: ["회수됨", "아직 회수되지 않음"],
  running: ["움직이는 중", "멈춤"],
  safe: ["안전함", "주의 필요"],
  safeToCross: ["건널 수 있음", "아직 건널 수 없음"],
  spinning: ["회전 중", "멈춤"],
  stable: ["안정됨", "불안정함"],
  stopped: ["멈춤", "움직이는 중"],
  struck: ["작동하거나 닿음", "아직 작동하거나 닿지 않음"],
  supported: ["받침 있음", "받침 없음"],
  tipped: ["기울어짐", "바로 서 있음"],
  accessReady: ["씨앗에 닿을 수 있음", "아직 닿을 수 없음"],
  actorOnly: ["용사만 통과할 수 있음", "누구나 통과할 수 있음"],
  arrowVisible: ["중력 화살표가 보임", "중력 화살표가 보이지 않음"],
  autoUnload: ["도착하면 자동으로 인출됨", "직접 꺼내야 함"],
  braked: ["층 브레이크가 잠김", "층 브레이크가 풀림"],
  danger: ["위험함", "안전하게 덮임"],
  dustVisible: ["흙가루가 방향을 보임", "흙가루가 보이지 않음"],
  fixedGravity: ["중력 방향이 고정됨", "중력 방향이 고정되지 않음"],
  fixedToPot: ["화분에 고정됨", "화분에서 분리됨"],
  fixedWhenMoving: ["운행 중 고정해야 함", "운행 중에도 뺄 수 있음"],
  handUsed: ["손을 사용 중", "손이 비어 있음"],
  illuminated: ["빛을 받고 있음", "빛을 받지 않음"],
  ladder: ["사다리로 오를 수 있음", "사다리가 아님"],
  lit: ["켜져 있음", "꺼져 있음"],
  optional: ["선택 소품", "필수 물건"],
  passageBlocked: ["통로가 막힘", "통로가 열려 있음"],
  persistentOpen: ["열린 상태가 유지됨", "다시 닫힐 수 있음"],
  potsCross: ["화분도 통과할 수 있음", "화분은 통과할 수 없음"],
  pressed: ["눌려 있음", "눌려 있지 않음"],
  recoverable: ["회수 가능", "회수할 수 없음"],
  reinforced: ["보강됨", "보강되지 않음"],
  relightable: ["다시 점화 가능", "다시 점화할 수 없음"],
  relightsWicks: ["심지를 다시 켤 수 있음", "심지를 다시 켤 수 없음"],
  requiresLitLantern: ["켜진 등불이 필요함", "꺼진 등불도 놓을 수 있음"],
  requiresTwoHands: ["두 손이 필요함", "한 손으로도 가능"],
  returned: ["반납됨", "아직 반납되지 않음"],
  safeRope: ["안전 밧줄이 있음", "안전 밧줄이 없음"],
  visible: ["윤곽이 보임", "윤곽이 보이지 않음"],
  centered: ["중앙 표식에 맞음", "중앙 표식에서 벗어남"],
  flame: ["불꽃이 유지됨", "불꽃이 꺼짐"],
  held: ["유지 중", "유지하지 않음"],
  high: ["올라감", "낮은 위치"],
  jump: ["점프 가능", "점프할 수 없음"],
  keeperAllowed: ["등지기도 이용 가능", "등지기는 이용할 수 없음"],
  loaded: ["평형추가 놓임", "평형추가 비어 있음"],
  lowered: ["지선이 내려옴", "지선이 아직 내려오지 않음"],
  rail: ["등지기 레일임", "등지기 레일이 아님"],
  railOnly: ["레일에서만 이동", "레일 밖도 이동 가능"],
  snuffed: ["불꽃이 꺼짐", "불꽃이 아직 꺼지지 않음"],
  stairs: ["계단으로 이동 가능", "계단으로 이동할 수 없음"],
  wedged: ["쐐기로 받침", "쐐기가 없음"],
};

export interface PresentedProperty {
  key: string;
  label: string;
  value: string;
}

export type PropertyVisibility = "shown" | "hidden" | "unknown";

export function formatMaterial(material: Entity["material"]): string {
  return MATERIAL_LABELS[material];
}

function resolveToken(token: string, world?: WorldState): string {
  if (token === "") return "없음";
  if (world?.entities[token]) return world.entities[token].name;
  const room = world && Object.values(world.entities).find(
    (entity) => entity.location.region === token && entity.properties.kind === "room-gravity-marker",
  );
  if (room) return room.name;
  const railOwner = world && Object.values(world.entities).find(
    (entity) => entity.properties.track === token,
  );
  if (railOwner) return `${railOwner.name} 레일`;
  if (token === "hero") return "용사";
  if (token === "keeper") return "등지기";
  if (token.startsWith("hand:")) return `${resolveToken(token.slice(5), world)}의 손`;
  const property = token.lastIndexOf(".");
  if (property > 0 && world?.entities[token.slice(0, property)]) {
    const entity = world.entities[token.slice(0, property)];
    const key = token.slice(property + 1);
    return `${entity.name}의 ${PROPERTY_LABELS[key] ?? key}`;
  }
  const split = token.lastIndexOf(":");
  if (split > 0) {
    const entity = token.slice(0, split);
    const state = token.slice(split + 1);
    if (world?.entities[entity])
      return `${world.entities[entity].name}이 ${resolveToken(state, world)}일 때`;
  }
  return ENUM_LABELS[token] ?? token;
}

export function formatScalar(
  value: Scalar,
  world?: WorldState,
  key?: string,
): string {
  if (typeof value === "boolean") {
    const states = key ? BOOLEAN_VALUES[key] : undefined;
    return states ? states[value ? 0 : 1] : value ? "예" : "아니요";
  }
  if (typeof value === "number")
    {
      const number = Number.isInteger(value)
      ? String(value)
      : String(Number(value.toFixed(2)));
      return key && QUANTITY_UNITS[key] ? `${number}${QUANTITY_UNITS[key]}` : number;
    }
  if (key === "receiver") {
    if (value === "a") return "왼쪽 수광판";
    if (value === "b") return "오른쪽 수광판";
  }
  if (value.includes("|") || value.includes(">") || value.includes("+"))
    return value
      .split("|")
      .flatMap((group) => group.split(/[>+]/))
      .map((token) => resolveToken(token, world))
      .join(" → ");
  return resolveToken(value, world);
}

export function propertyVisibility(key: string): PropertyVisibility {
  if (HIDDEN_PROPERTIES.has(key)) return "hidden";
  return Object.hasOwn(PROPERTY_LABELS, key) ? "shown" : "unknown";
}

export function formatProperty(
  world: WorldState,
  key: string,
  value: Scalar,
): PresentedProperty | null {
  if (propertyVisibility(key) !== "shown") return null;
  return {
    key,
    label: PROPERTY_LABELS[key],
    value: formatScalar(value, world, key),
  };
}

export function formatEntityFacts(world: WorldState, entity: Entity): string[] {
  const facts = [
    `위치 · 시작점에서 ${formatScalar(entity.location.x)}칸${entity.location.y === 0 ? "" : `, 높이 ${formatScalar(entity.location.y)}칸`}`,
    `재료 · ${formatMaterial(entity.material)}`,
    entity.movable ? "옮길 수 있음" : "고정되어 있음",
    `무게 · ${formatScalar(entity.weight)}칸`,
    entity.capacity === 0
      ? "수용 · 물건이나 사람을 실을 수 없음"
      : `수용 한계 · ${formatScalar(entity.capacity)}칸`,
    `닿는 거리 · ${formatScalar(entity.reach)}칸`,
  ];
  if (entity.parent) facts.push(`놓인 곳 · ${resolveToken(entity.parent, world)}`);
  for (const [key, value] of Object.entries(entity.properties)) {
    if (key === "capacity" && value === entity.capacity) continue;
    const presented = formatProperty(world, key, value);
    if (presented) facts.push(`${presented.label} · ${presented.value}`);
  }
  return facts;
}
