import { chromium, expect } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import { QUIET_EARLY_INTENT_CASES } from '../src/campaign/quiet/early';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors: string[] = [];
page.on('pageerror', (error) => errors.push(error.message));
let calls = 0;
let mode: 'ok' | 'error' | 'late' = 'ok';
let release: (() => void) | undefined;
await page.route('**/api/qa/campaign-interpret', async (route) => {
  calls++;
  const input = route.request().postDataJSON();
  const action = QUIET_EARLY_INTENT_CASES.find((row) => row.segmentId === input.world.segmentId)!;
  if (mode === 'late') await new Promise<void>((resolve) => { release = resolve; });
  if (mode === 'error') return route.fulfill({ status: 422, json: { error: { message: '잠깐 뜻을 읽지 못했어요.' } } });
  await route.fulfill({ json: { program: { version: 2, id: `fixture-${calls}`, text: input.text, model: 'browser-fixture', scope: { stageId: input.stageId, region: input.world.segmentId }, guard: false, body: action.body } } }).catch(() => {});
});
try {
  await page.goto('http://localhost:5173/?qa=1');
  await page.locator('.roadmap-stop').filter({ has: page.getByRole('heading', { name: '비에 잠긴 회랑', exact: true }) }).getByRole('button', { name: /들어가기/ }).click();
  const input = page.locator('textarea[data-play-command]');
  await expect(input).toBeVisible();
  expect(await page.getByRole('button', { name: /뜻 확인|이 뜻으로|이 메모로 출발/ }).count()).toBe(0);
  await input.fill('상자를 옆으로 밀고 나가');
  await input.dispatchEvent('compositionstart');
  await input.press('Enter');
  expect(calls).toBe(0);
  await input.dispatchEvent('compositionend');
  await input.press('Shift+Enter');
  expect(calls).toBe(0);
  mode = 'error';
  await input.press('Enter');
  await expect(page.getByRole('alert')).toContainText('뜻을 읽지 못했어요');
  await expect(input).toHaveValue(/상자를/);
  mode = 'late';
  await input.press('Enter');
  await expect.poll(() => calls).toBe(2);
  await page.getByRole('button', { name: '취소', exact: true }).click();
  release?.();
  await expect(input).toHaveValue(/상자를/);
  await expect(page.getByRole('combobox', { name: 'QA 스테이지 선택' })).toHaveValue('02-v2-1');
  mode = 'ok';
  await input.press('Enter');
  await input.press('Enter').catch(() => {});
  await expect(page.getByRole('combobox', { name: 'QA 스테이지 선택' })).toHaveValue('02-v2-2');
  expect(calls).toBe(3);
  await page.reload();
  await page.locator('.roadmap-stop').filter({ has: page.getByRole('heading', { name: '비에 잠긴 회랑', exact: true }) }).getByRole('button', { name: /이어 걷기/ }).click();
  await expect(page.getByRole('combobox', { name: 'QA 스테이지 선택' })).toHaveValue('02-v2-2');
  await expect(input).toHaveValue('');
  await mkdir('artifacts/quiet-command', { recursive: true });
  await page.screenshot({ path: 'artifacts/quiet-command/desktop.png', fullPage: true });
  await writeFile('artifacts/quiet-command/report.json', JSON.stringify({ calls, errors, scope: 'Shared composer Enter/IME/ShiftEnter/error/cancel/duplicate prevention and real runtime save/reload; provider fixture, zero live AI.' }, null, 2));
  expect(errors).toEqual([]);
  console.log('PASS shared campaign command: Enter directly executes, IME/ShiftEnter/cancel/error/duplicate/reload; 3 fixture requests');
} finally { release?.(); await browser.close(); }
